import { useState, useEffect } from "react";
import { RefreshCw, Download, FileCode2, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { commands } from "@/lib/tauri-commands";
import { useLogStore } from "@/stores/logStore";

export function ConfigPreview() {
  const [preview, setPreview] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [writing, setWriting] = useState(false);
  const { addLog } = useLogStore();

  const loadPreview = async () => {
    setLoading(true);
    try {
      const config = await commands.previewSshConfig();
      setPreview(config);
    } catch (err) {
      setPreview(`Error: ${err}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPreview();
  }, []);

  const handleWrite = async () => {
    if (!confirm("Write SSH config? A backup will be created first.")) return;
    setWriting(true);
    try {
      const backupPath = await commands.backupSshConfig().catch(() => null);
      await commands.writeSshConfig();
      addLog({
        action: "config",
        detail: `SSH config written${backupPath ? ` (backup: ${backupPath})` : ""}`,
        level: "info",
      });
      toast.success("SSH config written", {
        description: backupPath ? `Backup saved to ${backupPath}` : undefined,
      });
    } catch (err) {
      addLog({ action: "config", detail: `Failed: ${err}`, level: "error" });
      toast.error("Failed to write config", { description: String(err) });
    } finally {
      setWriting(false);
    }
  };

  return (
    <div className="space-y-4 max-w-3xl">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileCode2 size={16} className="text-primary" />
          <h3 className="text-sm font-semibold">SSH Config Preview</h3>
          <span className="text-[10px] text-muted-foreground font-mono">~/.ssh/config</span>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={loadPreview}
            disabled={loading}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg bg-secondary hover:bg-secondary/80 transition-colors disabled:opacity-50"
          >
            <RefreshCw size={12} className={loading ? "animate-spin" : ""} />
            Refresh
          </button>
          <button
            type="button"
            onClick={handleWrite}
            disabled={writing}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
          >
            {writing ? <Loader2 size={12} className="animate-spin" /> : <Download size={12} />}
            {writing ? "Writing..." : "Write Config"}
          </button>
        </div>
      </div>
      <div className="rounded-lg border overflow-hidden">
        <div className="px-4 py-2 bg-secondary/50 border-b">
          <span className="text-[10px] text-muted-foreground font-mono">
            # Generated by Maze SSH
          </span>
        </div>
        <pre className="p-4 text-sm font-mono whitespace-pre-wrap overflow-auto max-h-96 bg-card leading-relaxed">
          {loading ? (
            <span className="text-muted-foreground flex items-center gap-2">
              <Loader2 size={14} className="animate-spin" /> Loading...
            </span>
          ) : (
            preview || <span className="text-muted-foreground">No profiles configured yet.</span>
          )}
        </pre>
      </div>
    </div>
  );
}
